### ISSUE TITLE
How to compile it into a binary?

### ISSUE THREAD

**Issue by d1y** [slint-ui/slint-nodejs-template#1]
bindings for nodejs

**Comment by tronical** [comment]
Thanks for posting here. That's a very valid question and unfortunately we don't have a good documented answer today :(

As part of https://github.com/slint-ui/slint/issues/961 we're discussing an upgrade to napi for our nodejs bindings. In that context we're also discussing the option of including Slint as binaries. That in turn should pave the way to use something like https://github.com/vercel/pkg for you to create a binary package. You might even be able to use https://github.com/vercel/pkg today, I'm not sure.

Closing this as not-planned for this template, as https://github.com/slint-ui/slint/issues/961 is for tracking the Slint side of it, including documentation for deployment.
