### ISSUE TITLE
Cant install Slint-ui

### ISSUE THREAD

**Issue by dennismargraf** [slint-ui/slint-nodejs-template#3]
![Screenshot 2024-01-22 114851](https://github.com/slint-ui/slint-nodejs-template/assets/142588289/267d1c18-e765-4606-858f-cbced2563c90)

as seen on the Photo its not possible for me to install slint-ui, cause of cargo

**Comment by dennismargraf** [comment]
Needed to install Rust again

**Comment by tronical** [comment]
Yes indeed. This will be addressed in the upcoming 1.4 release as part of https://github.com/slint-ui/slint/issues/1991 :-).

If you're daring, you can already try it by changing `"slint-ui": "^1.3.0"` to `"slint-ui": "nightly"`.
